name: Your Fork

on:
  pull_request_target:
    types: [opened]

jobs:
  close:
    if: github.repository == 'hashicorp-education/fiap-postech-infra'
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}